### ISSUE TITLE
Rewrite of the stupid cog 

### ISSUE THREAD

**Issue by JeffJrShim** [JeffJrShim/noa-cord-rules-cog#2]
```py
Exception during loading of package
Traceback (most recent call last):
  File "C:\Users\USER\noa\lib\site-packages\redbot\core\core_commands.py", line 176, in _load
    await bot.load_extension(spec)
  File "C:\Users\USER\noa\lib\site-packages\redbot\core\bot.py", line 1519, in load_extension
    lib.setup(self)
  File "C:\Users\USER\Downloads\Noa Fukushima\data\cogs\CogManager\cogs\noacordrules\__init__.py", line 5, in setup
    bot.add_cog(NoaCordRules(bot))
  File "C:\Users\USER\noa\lib\site-packages\redbot\core\bot.py", line 1630, in add_cog
    raise RuntimeError(
RuntimeError: The NoaCordRules cog in the noacordrules.noacordrules package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.
```

**Comment by JeffJrShim** [comment]
doesnt need a rewrite anymore
